#!/usr/bin/bash

# add new blogs
# this is still a work in progress

echo "pre-commit hook"

posts=`ls blog | grep -v "record.txt"`

for post in $posts; do
    title=`echo $post |
        sed -E 's/(\w+)\.\w+/\1/g' |
        sed 's/_/ /g' |
        sed 's/\b\(.\)/\u\1/g'
        `
    birth_stat=`stat --format=%w`
    birth=`date -d "$(birth_stat)"`
    last_edit=`date -r $post`
done

exit 0;
